### ISSUE TITLE
Laser mode

### ISSUE THREAD

**Issue by dplund** [Schildkroet/GRBL-Advanced#1]
I got it to run on my nucleo board and configured it for laser engraving, thanks for sharing this!

Is there a way to turn on laser mode for this version? The settings menu doesn't provide an option for this, is it commented out or just not included?

When rastering (adjusting spindle speed/laser power after each block) programs run very slow, about 1 block per second. If the spindle speed is not being changed, such as for profiling, the controller has no problem cranking through the moves, but when it comes to turn the laser off and then back on again to get from one profile to the next, it has the same 1 second or so pause. Any ideas how to fix this?

It seems it will only connect at 115200 baud. This probably won't be a limitation, but for grayscale rastering it can push the limits of the bandwidth, I am running my STM32F103 at 230400 baud and the buffer occasionally does dip below half.

Thanks in advance for your consideration and help.

**Comment by Schildkroet** [comment]
Since this project was intended for my CNC mill, i didn't care about laser mode. I even might have removed some code for laser  mode...? GRBL settings etc stayed the same, so you should check grbl1.1 for laser mode and how to configure it. If settings don't work, you have to look into source code for changes.

For the speed problems:
1. Make sure you set the Target in EmBitz to 'Release'. It uses optimizations and programs are usually twice as fast as Debug Target.
2. I tried to be as much compatible with grbl as possible, so i set the baudrate to 115200. But you can change it to 230400 (or even more) in grbl/Config.h. 
In HAL/USART/USART_FIFO.h you can also increase the serial buffer. The mcu has plenty of RAM left. But this works only, if you tell your streaming software, about the extended buffer.
In grbl/Config.h you can also increase sizes for planner etc.

mfg

**Comment by Schildkroet** [comment]
Meanwhile I also made some changes in clock tree and serial report, which are not fully correct in the current version. I will probably push it in a few days and will then also increase the serial buffer etc. since it doesn't matter.

Sooner (or later) chamnit will release a ARM version of grbl with many improvements, I will continue my work from there for 1:1 compability with grbl. So this is just a step in between which works, but is not perfect.

**Comment by dplund** [comment]
Thanks for looking into this. I'll work on the laser mode and let you know
if I make any progress I think might be helpful.

On Apr 23, 2018 6:28 AM, "Schildkroet" <notifications@github.com> wrote:

Closed #1 <https://github.com/Schildkroet/GRBL-Advanced/issues/1>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Schildkroet/GRBL-Advanced/issues/1#event-1589142131>,
or mute the thread
