### ISSUE TITLE
Slow '$x=val' Commands

### ISSUE THREAD

**Issue by DamonJSmith** [Schildkroet/GRBL-Advanced#10]
Hi,

So I was using GRBL on an Arduino but decided to move to your STM32 build. I have compiled and flashed it to a STM32F411 Nucleo board but I'm having a problem where there is a large delay (Around one second) whenever I send it setting commands ($x=val) and receiving the 'ok' response. There seems to be no problems with the other g-code commands.

Thanks.

**Comment by Schildkroet** [comment]
Since the stm32 has no internal EEPROM, it must be simulated using the flash memory. Unfortunately the flash doesn't support single byte write.
So for every val-command an entire flash page must be deleted and written again. This procedure takes it time.
For better performance you must add an external EEPROM/memory.
