### ISSUE TITLE
Clarification on encoder

### ISSUE THREAD

**Issue by Steph101** [Schildkroet/GRBL-Advanced#70]
Does the system use a single pulse or AB encoder for threading feedback and which pins are used for this?

**Comment by ClockedLogic** [comment]
Looking at the code it appears to count pulses per rev which indicates AB phases for proper quadrature.  In fact only A and index are required although the code doesn't mention the pins connected it uses tim2 for the encoder but there is no initialisation code.  You would need one pin for phase A or B input and a second pin for Index to reset the counter.   
TIM4 init code contains the following comment. 

  //Remap Encoder pins to PB8 and PB9. Previosly on 6 an7 where I2C1 should be

look at the function TIM4_Init in TIM.C and you see it is configured for the encoder on pins PB8 and PB9 although I cant tell which pin is phase input or index input.  It may just take both phase A and B quadrature for counting up and down but this is not  right for lathe spindle sinchronised motion . You need to use the index pulse to reset the counter in order to count pulses per rev.

**Comment by Schildkroet** [comment]
Hello,
currently i'm using an AB encoder. It is connectecd to PB 6/7
https://github.com/Schildkroet/GRBL-Advanced/blob/software/HAL/TIM/TIM.c#L136-L183

But it is still experimental and you have to set the prescaler and PULSES_PER_REV according to your encoder
